baseURL = "http://example.org/"
languageCode = "en-us"
title = "Hugo Demo Site"
paginate = 5
theme = "hugo-Papermod"

enableRobotsTXT = true

[module]

  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"
    disable=false

[minify]
  disableXML = true
  minifyOutput = true

[params]
  title = "Hugo Demo Site"
  description = "A quick site to demostrate custom features that have been written by zjeaton"
  author = "Zak"

  ShowShareButtons = true
  comments = false
  defaultTheme = "dark" # auto or dark
  # [ "/css/styles.css", "/css/custom.css", etc. ] place into /static/css
  customCSS = [ 
    "/css/styles.css", 
    "/css/image-modal.css" 
  ]

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true


[menu]
[[menu.main]]
identifier = "image-modal"
name = "Image-Modal"
url = "/modal"
weight = 1
