[build]
	base = "/"
	command = "hugo"
	context = "production"
	publish = "public"

[build.processing]
	skip_processing = true

[context.production.environment]
	HUGO_VERSION = "0.78.1"
	HUGO_ENV = "production"