name = "github pages"

[on.push]
branches = [ "main" ]

[jobs.deploy]
runs-on = "ubuntu-18.04"

  [[jobs.deploy.steps]]
  uses = "actions/checkout@v2"

    [jobs.deploy.steps.with]
    submodules = true
    fetch-depth = 0

  [[jobs.deploy.steps]]
  name = "Setup Hugo"
  uses = "peaceiris/actions-hugo@v2"

    [jobs.deploy.steps.with]
    hugo-version = "0.75.1"
    extended = true

  [[jobs.deploy.steps]]
  name = "Build"
  run = "hugo --minify"

  [[jobs.deploy.steps]]
  name = "Deploy"
  uses = "peaceiris/actions-gh-pages@v3"

    [jobs.deploy.steps.with]
    github_token = "${{ secrets.GITHUB_TOKEN }}"
    publish_dir = "./public"
